### ISSUE TITLE
Logo Images for tech-stacks not available due to migration at source

### ISSUE THREAD

**Issue by khantiRindani** [Lissy93/web-check#36]
### Issue: 
Recently, I came across this issue: Logo Image in tech-stack card is not visible and name is shown as fallback text.

<picture>
<img src=https://github.com/Lissy93/web-check/assets/36477517/35a2032b-1448-40fb-9969-d05cf091a8ec width=300px />
</picture>

### Cause:
On the source app of [wappalyzer](https://github.com/wappalyzer/wappalyzer), image logo files are migrated to new location. 

Old Location: https://raw.githubusercontent.com/wappalyzer/wappalyzer/master/src/drivers/webextension/images/icons/
New Location: https://raw.githubusercontent.com/wappalyzer/wappalyzer/master/src/images/icons/

### Required change:
Updating the path in [`TechStack.tsx`](https://github.com/Lissy93/web-check/blob/master/src/components/Results/TechStack.tsx#L83)

Successfully tested in local:
<picture>
<img src=https://github.com/Lissy93/web-check/assets/36477517/a2f854cd-2be7-4968-aeb7-b7ed31edd334 width=300px />
</picture>

**Comment by Lissy93** [comment]
Thanks @khantiRindani for the detailed ticket
I've pushed a fix out for this :)

Although sadly this feature might not be around for much longer, as the author of Wappalyzer has made the project private. I'm working on a fork of it at the moment.

https://twitter.com/ITSecurityguard/status/1694674956204880132

**Comment by khantiRindani** [comment]
Got it, thanks @Lissy93 for sharing. Do you think if it's possible to ask wappalyzer for a feature request where image is also part of the API response? We would be free from github repo dependency. The limitations with free tier of API usage would still be there though.

**Comment by Lissy93** [comment]
Well it's already using icons from their CDN, rather than the GitHub (updated in 49cfad2dbe00325fe4668af9786b6f014a611169)

https://github.com/Lissy93/web-check/blob/6d8b2368e7dc8a128d08acc9d172995a727cffde/src/components/Results/TechStack.tsx#L83


I'm affraid that using the Wappalyzer API is not an option. Their API has no free tier, and [pricing starts from](https://www.wappalyzer.com/pricing/) $250/month for only 5000 requests. I can't afford that, even for testing. 

But feel free to fork the repo, if you'd like to add support for Wappalyzer API (you'll need your own keys to develop this).

**Comment by Lissy93** [comment]
Alternativley, I've got a fork of Wappalyzer which I'm going to be maintaining here: https://github.com/Lissy93/wapalyzer 
The [original version](https://github.com/wappalyzer/) is no longer available on GitHub.

**Comment by khantiRindani** [comment]
Got it, thanks @Lissy93.
