### ISSUE TITLE
3 checks giving error.

### ISSUE THREAD

**Issue by BLACK-SCORP10** [Lissy93/web-check#5]
![image](https://github.com/Lissy93/web-check/assets/102329978/a85039bf-fe5d-43ac-8f36-018f73e263c8)
Here these 3 checks are getting failed every time.

**Comment by Lissy93** [comment]
there should be a note explaining why that happens if you scroll down just a tiny bit further. But you can see the error, or retry the task using the buttons or via the console.

If you self-host your own instance, you won't be constrained by my empty bank account 😅

**Comment by Lissy93** [comment]
Could you share a few more details, so I can look into it:
- The domain you're testing
- The full error log and content of the console
- Using demo instance, or self-hosting?
- You're environment, e.g. browser, and any other steps you took, so I can try and reproduce

Thanks :)

**Comment by Lissy93** [comment]
Heya @BLACK-SCORP10 

I've pushed some updates, and have also (maybe temporarily) upgraded the running instance to a Pro plan on Netlify, and they've [upgraded my function timeout](https://answers.netlify.com/t/function-timeout-increase/53881/438?u=lissy93) to 26 sec, so you should no longer see any errors :)

I plan to push out a Docker version soon, so in the long term I recommend you run your own instance if you plan to use the app heavily. Because I don't know how long I'll be able to afford the Netlify Pro plan for, and the free tier work great for 90% of cases.
